# Compare the actual versioned keg with a fresh, native-relocated verified bottle.
# Called only with candidate/attestation checks complete and native locks held.
require "digest"
require "find"
require "keg"
require "formula_installer"
require "sbom"
require "time"

module BrewWardenPayload
  MAX_FILES = 100_000
  MAX_BYTES = 2 * 1024 * 1024 * 1024

  def self.store_snapshot(root, value)
    data = JSON.generate(value)
    raise "state snapshot exceeds limit" if data.bytesize > 8 * 1024 * 1024
    digest = Digest::SHA256.hexdigest(data)
    file = root/"states/#{digest}.json"
    if file.exist? || file.symlink?
      raise "saved state snapshot changed" unless file.file? && !file.symlink? && file.size == data.bytesize && file.binread == data
    else
      pending = Pathname("#{file}.pending")
      pending.open(File::WRONLY | File::CREAT | File::EXCL, 0o600) { |output| output.write(data); output.fsync }
      pending.rename(file)
      file.dirname.open { |directory| directory.fsync }
    end
    digest
  end

  def self.inventory(root)
    raise "invalid keg root" unless root.directory? && !root.symlink? && root.realpath == root
    rows = {}
    bytes = 0
    Find.find(root.to_s) do |name|
      path = Pathname(name)
      next if path == root
      raise "keg inventory exceeds limit" if rows.length >= MAX_FILES
      relative = path.relative_path_from(root).to_s
      stat = path.lstat
      mode = stat.mode & 0o7777
      raise "privileged keg permissions" unless (mode & 0o7000).zero?
      rows[relative] = if stat.symlink?
        ["link", path.readlink.to_s]
      elsif stat.directory?
        ["directory", mode]
      elsif stat.file?
        bytes += stat.size
        raise "keg payload exceeds limit" if stat.size > 128 * 1024 * 1024 || bytes > MAX_BYTES
        ["file", mode, stat.size, Digest::SHA256.file(path).hexdigest]
      else
        raise "unsupported keg file type"
      end
    end
    rows
  end

  def self.verify(formula, workspace)
    actual = HOMEBREW_CELLAR/formula.name/formula.pkg_version.to_s
    raise "candidate keg is not active" unless formula.opt_prefix.symlink? && formula.opt_prefix.realpath == actual
    before = inventory(actual)
    Dir.mktmpdir("payload-", workspace.to_s) do |directory|
      stage = Pathname(directory)
      # Native linkage repair strips paths inside HOMEBREW_TEMP. Reconstruction
      # must be outside that build directory, or valid @loader_path rpaths get
      # removed merely because the verified copy is private.
      temp = HOMEBREW_TEMP.realpath.to_s
      raise "payload reconstruction inside build temporary directory" if stage.to_s == temp || stage.to_s.start_with?(temp + "/")
      snapshot = stage/"verified.bottle.tar.gz"
      FileUtils.copy_file(formula.bottle.cached_download, snapshot)
      formula.bottle.verify_download_integrity(snapshot)
      UnpackStrategy.detect(snapshot, prioritize_extension: true, temporary_directory: stage)
                    .extract_nestedly(to: stage, basename: formula.bottle.downloader.basename, prioritize_extension: true)
      snapshot.unlink
      expected = stage/formula.name/formula.pkg_version.to_s
      raise "unexpected bottle layout" unless stage.children == [stage/formula.name] && (stage/formula.name).children == [expected]
      # Keg requires a real installed Cellar path. Retain its verified identity
      # and native relocation implementation, redirecting only the payload path.
      # This private API is pinned and covered by real VM byte comparisons.
      keg = Keg.new(actual)
      keg.instance_variable_set(:@path, expected)
      tab = Utils::Bottles.load_tab(formula)
      skip = formula.bottle_specification.skip_relocation?(tab:)
      keg.replace_placeholders_with_locations(tab.changed_files, skip_linkage: skip, linkage_files: tab.linkage_files)
      build_cellar = tab.built_prefix ? "#{tab.built_prefix}/Cellar" : Utils::Bottles.tag.default_cellar
      build_prefix = Pathname(build_cellar).parent.to_s
      # Absolute links would need a separately verified logical destination
      # mapping when reconstruction occurs outside the installed Cellar.
      if build_prefix != HOMEBREW_PREFIX.to_s
        raise "unsupported bottle symlink relocation" if inventory(expected).values.any? { |entry| entry[0] == "link" && Pathname(entry[1]).absolute? }
      end
      keg.fix_dynamic_linkage unless skip
      compare_sbom(expected, actual, formula)
      wanted = inventory(expected)
      got = inventory(actual)
      raise "keg changed during verification" unless got == before
      # INSTALL_RECEIPT is generated by Homebrew, not part of these bottles.
      # Its semantic identity and dependency fields are checked by Candidate.
      raise "unexpected packaged receipt" if wanted.key?("INSTALL_RECEIPT.json")
      receipt = got.delete("INSTALL_RECEIPT.json")
      raise "missing installed receipt" unless receipt && receipt[0] == "file" && receipt[1] == 0o644 && receipt[2] <= 1024 * 1024
      raise "installed payload differs from verified bottle" unless wanted == got
    end
    Digest::SHA256.hexdigest(JSON.generate(before.sort.to_h))
  end

  def self.compare_sbom(expected, actual, formula)
    source = expected/SBOM::FILENAME
    installed = actual/SBOM::FILENAME
    raise "missing bottle SBOM" unless source.file? && !source.symlink? && installed.file? && !installed.symlink?
    raise "SBOM exceeds limit" if source.size > 4 * 1024 * 1024 || installed.size > 4 * 1024 * 1024
    info = JSON.parse(installed.read).fetch("creationInfo")
    created = info.fetch("created")
    timestamp = Time.iso8601(created)
    raise "invalid installed SBOM date" unless timestamp.utc.iso8601 == created && timestamp.to_i.positive? && timestamp <= Time.now
    creators = info.fetch("creators")
    raise "invalid installed SBOM creator" unless creators.is_a?(Array) && creators.length == 1 && creators[0].is_a?(String)
    match = creators[0].match(%r{\ATool: https://github\.com/Homebrew/brew@([a-zA-Z0-9.+_-]{1,128}|>=4\.3\.0 \(shallow or no git repository\))\z})
    raise "unsupported installed SBOM creator" unless match
    SBOM.update_pour_metadata(source, homebrew_version: match[1], time: timestamp.to_i, supplement: formula.bottle.sbom_supplement)
  end
end
