package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"
)

func readabilityScriptFixture(t *testing.T, tools ...string) string {
	t.Helper()
	root := t.TempDir()
	for _, tree := range []string{"scripts", "tools", "internal", "cmd", "tests", ".cache/tools", ".githooks"} {
		if err := os.MkdirAll(filepath.Join(root, tree), 0o700); err != nil {
			t.Fatal(err)
		}
	}
	for _, name := range []string{"env.sh", "tools.sh", "tool-versions.env", "format.sh", "check.sh"} {
		raw, err := os.ReadFile(filepath.Join("../../scripts", name))
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(filepath.Join(root, "scripts", name), raw, 0o700); err != nil {
			t.Fatal(err)
		}
	}
	if err := os.WriteFile(filepath.Join(root, ".githooks", "pre-commit"), []byte("#!/bin/sh\nexit 0\n"), 0o700); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, "go.mod"), []byte("module example.org/readability-fixture\n\ngo 1.24.0\n"), 0o600); err != nil {
		t.Fatal(err)
	}
	for _, name := range tools {
		binary, err := filepath.Abs(filepath.Join("../../.cache/tools", name))
		if err != nil {
			t.Fatal(err)
		}
		if _, err := os.Stat(binary); os.IsNotExist(err) {
			t.Skipf("explicit tool setup required for %s integration test", name)
		} else if err != nil {
			t.Fatal(err)
		}
		if err := os.Symlink(binary, filepath.Join(root, ".cache/tools", name)); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func TestFormatterRefusesMissingOrUnpinnedTool(t *testing.T) {
	root := readabilityScriptFixture(t)
	run := func(want string) {
		t.Helper()
		command := exec.Command("sh", "scripts/format.sh", "check")
		command.Dir = root
		output, err := command.CombinedOutput()
		if err == nil || !strings.Contains(string(output), want) {
			t.Fatalf("want refusal %q, got %v: %s", want, err, output)
		}
	}
	run("Missing gofumpt")
	command := exec.Command("go", "build", "-o", filepath.Join(root, ".cache/tools/gofumpt"), ".")
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("build unpinned substitute: %v: %s", err, output)
	}
	run("Wrong gofumpt version")
}

func TestFormatterChecksAndRepairsTaggedAndFixtureSources(t *testing.T) {
	root := readabilityScriptFixture(t, "gofumpt", "shfmt")
	original := "//go:build vmacceptance\n\npackage fixture\n\nconst mode = 0700\nfunc first() {\n\tprintln(mode)\n}\nfunc second() {\n\tprintln(`{\"field\":true}`)\n}\n"
	paths := []string{"tests/tagged_test.go", "internal/testdata/generated.go"}
	for _, name := range paths {
		path := filepath.Join(root, name)
		if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
			t.Fatal(err)
		}
		content := original
		if strings.HasSuffix(name, "generated.go") {
			content = "// Code generated by fixture. DO NOT EDIT.\n" + content
		}
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
	}
	run := func(mode string) (string, error) {
		t.Helper()
		command := exec.Command("sh", "scripts/format.sh", mode)
		command.Dir = root
		output, err := command.CombinedOutput()
		return string(output), err
	}
	output, err := run("check")
	if err == nil || !strings.Contains(output, "Run ./scripts/format.sh write") {
		t.Fatalf("gofmt-clean readability drift passed: %v: %s", err, output)
	}
	for _, name := range paths {
		if !strings.Contains(output, name) {
			t.Fatalf("formatter omitted %s: %s", name, output)
		}
	}
	unchanged, err := os.ReadFile(filepath.Join(root, paths[0]))
	if err != nil || string(unchanged) != original {
		t.Fatalf("check mode changed source: %v: %q", err, unchanged)
	}
	if output, err := run("write"); err != nil {
		t.Fatalf("repair failed: %v: %s", err, output)
	}
	if output, err := run("check"); err != nil {
		t.Fatalf("repaired source rejected: %v: %s", err, output)
	}
	repaired, err := os.ReadFile(filepath.Join(root, paths[0]))
	if err != nil || !strings.Contains(string(repaired), "0o700") || !strings.Contains(string(repaired), "}\n\nfunc second") || !strings.Contains(string(repaired), "`{\"field\":true}`") {
		t.Fatalf("repair lost formatting or literal bytes: %v: %s", err, repaired)
	}
	if err := os.WriteFile(filepath.Join(root, paths[0]), []byte("package fixture\nfunc broken("), 0o600); err != nil {
		t.Fatal(err)
	}
	if output, err := run("check"); err == nil || !strings.Contains(output, "expected") {
		t.Fatalf("formatter parse failure became success: %v: %s", err, output)
	}
}

func TestLintRejectsIdentifierAndReceiverDrift(t *testing.T) {
	root := readabilityScriptFixture(t, "staticcheck", "gofumpt", "shfmt")
	path := filepath.Join(root, "internal", "fixture.go")
	bad := `package fixture

var ArtifactId = "bottle"

type Runtime struct{}

func (copied Runtime) First() string {
	var value string = "bottle"
	return value + ArtifactId
}

func (installed Runtime) Second() string { return ArtifactId }
`
	if err := os.WriteFile(path, []byte(bad), 0o600); err != nil {
		t.Fatal(err)
	}
	run := func() (string, error) {
		t.Helper()
		command := exec.Command("sh", "scripts/check.sh", "lint")
		command.Dir = root
		output, err := command.CombinedOutput()
		return string(output), err
	}
	output, err := run()
	if err == nil || !strings.Contains(output, "ST1003") || !strings.Contains(output, "ST1016") || !strings.Contains(output, "ST1023") {
		t.Fatalf("want naming, receiver and redundant-type findings, got %v: %s", err, output)
	}
	good := strings.ReplaceAll(bad, "ArtifactId", "ArtifactID")
	good = strings.ReplaceAll(good, "var value string =", "value :=")
	good = strings.ReplaceAll(good, "installed Runtime", "copied Runtime")
	if err := os.WriteFile(path, []byte(good), 0o600); err != nil {
		t.Fatal(err)
	}
	if output, err := run(); err != nil {
		t.Fatalf("corrected identifiers rejected: %v: %s", err, output)
	}
}

func TestShellFormatterRepairsScriptsAndHooksWithoutChangingArguments(t *testing.T) {
	root := readabilityScriptFixture(t, "gofumpt", "shfmt")
	original := "#!/bin/sh\nset -- 'a b' 'c;d'\nif [ \"$#\" -eq 2 ];then printf '%s\\n' \"$1\" \"$2\";fi\n"
	for _, name := range []string{"scripts/fixture.sh", ".githooks/pre-commit"} {
		if err := os.WriteFile(filepath.Join(root, name), []byte(original), 0o700); err != nil {
			t.Fatal(err)
		}
	}
	run := func(mode string) (string, error) {
		t.Helper()
		command := exec.Command("sh", "scripts/format.sh", mode)
		command.Dir = root
		output, err := command.CombinedOutput()
		return string(output), err
	}
	output, err := run("check")
	if err == nil || !strings.Contains(output, "scripts/fixture.sh") || !strings.Contains(output, ".githooks/pre-commit") {
		t.Fatalf("script/hook formatting drift passed: %v: %s", err, output)
	}
	unchanged, err := os.ReadFile(filepath.Join(root, "scripts/fixture.sh"))
	if err != nil || string(unchanged) != original {
		t.Fatalf("shell check changed source: %v: %q", err, unchanged)
	}
	if output, err := run("write"); err != nil {
		t.Fatalf("shell repair failed: %v: %s", err, output)
	}
	if output, err := run("check"); err != nil {
		t.Fatalf("repaired shell rejected: %v: %s", err, output)
	}
	command := exec.Command("sh", "scripts/fixture.sh")
	command.Dir = root
	outputBytes, err := command.CombinedOutput()
	if err != nil || string(outputBytes) != "a b\nc;d\n" {
		t.Fatalf("formatter changed argument boundaries: %v: %q", err, outputBytes)
	}
	if err := os.WriteFile(filepath.Join(root, "scripts/fixture.sh"), []byte("#!/bin/sh\nif [ yes ]; then\n"), 0o700); err != nil {
		t.Fatal(err)
	}
	if output, err := run("check"); err == nil || !strings.Contains(output, "fi") {
		t.Fatalf("shell parse failure became success: %v: %s", err, output)
	}
}

func TestShellFormatterRefusesMissingOrUnpinnedTool(t *testing.T) {
	root := readabilityScriptFixture(t, "gofumpt")
	run := func(want string) {
		t.Helper()
		command := exec.Command("sh", "scripts/format.sh", "write")
		command.Dir = root
		output, err := command.CombinedOutput()
		if err == nil || !strings.Contains(string(output), want) {
			t.Fatalf("want refusal %q, got %v: %s", want, err, output)
		}
	}
	run("Missing shfmt")
	command := exec.Command("go", "build", "-o", filepath.Join(root, ".cache/tools/shfmt"), ".")
	if output, err := command.CombinedOutput(); err != nil {
		t.Fatalf("build unpinned shell formatter: %v: %s", err, output)
	}
	run("Wrong shfmt version")
}
